version: 2
jobs:
  build:
    working_directory: ~/circleci-sg-ldap
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    resource_class: large
    steps:
      - checkout
      #- restore_cache:
      #    key: circleci-sg-ldap-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      #- save_cache:
      #    paths:
      #      - ~/.m2
      #    key: circleci-sg-ldap-{{ checksum "pom.xml" }}
      - run: mvn package
      #- store_test_results:
      #    path: target/surefire-reports
      #- store_artifacts:
      #    path: target/xxx.jar
